### ISSUE TITLE
Auto-Restart Doesn't work with EGS Version - Can't Authenticate after restart

### ISSUE THREAD

**Issue by Targren** [Rfvgyhn/min-ed-launcher#10]
When I enable the Auto-Restart function, the game client auto-restarts correctly, but once the game is loaded, the message "LOGIN FAILURE: The game failed to communicate with the authentication server. Please check your internet connection and try again in a few minutes."  Further restarts have the same problem. 

I don't know if this is even something you can fix, or just another thing on the "Doesn't work right on Epic" list, but I wanted to be sure you were aware of it.

**Comment by Rfvgyhn** [comment]
How long had you been in-game before trying to restart? It's possible the epic auth token expired and there's a bug with the token refresh logic.

**Comment by Targren** [comment]
I thought about that, so I started the game, exited immediately, and the same thing still happened. Less than 30 seconds in game.

**Comment by Rfvgyhn** [comment]
Sorry it's taken so long to respond. I looked into it and it seems like once ED launches, it refreshes the auth token which invalidates the launcher's auth token. The default launcher's fix for this is to just shut down the launcher and make you re-launch via the Epic launcher. I'm not sure if there's a fix for this. I'll leave this open for a bit while I mull it over. Maybe there's a solution I'm not thinking of.

**Comment by Rfvgyhn** [comment]
Short of searchng for the token in Elite's memory (which, IMO, is too much effort for the return), I don't think this issue can be solved. I'll add a note to the readme stating the restart functionality doesn't work with Epic accounts.

If anyone has a potential solution, please share.
