### ISSUE TITLE
Not Working with Windows Steam %command%

### ISSUE THREAD

**Issue by RanykT** [rfvgyhn/min-ed-launcher#100]
I just installed this, following the instructions. Here are my experiences. I'm on Windows 10 using Steam.

cmd /d "MinEdLauncher.exe %command% /autorun /autoquit /edo" opens command prompt.
cmd /d "MinEdLauncher.exe %command% /autorun /autoquit /edh4" opens command prompt.
cmd /d "MinEdLauncher.exe %command%" opens command prompt.
cmd /d "MinEdLauncher.exe /autorun /autoquit /edo" opens the launcher.

What am I missing? I literally can't get this to work. I even tried to just start the .exe from the command prompt that opens and get
[21:01:36 INF] Logging in
[21:01:37 ERR] Unhandled exception: System.NotImplementedException: Arg_NotImplementedException

**Comment by RanykT** [comment]
Ok, I see, it's fake. After fiddling with everything, instead of defining the D drive, like I expected, I tried /c instead of /d. And it works...This seems odd to me.

**Comment by rfvgyhn** [comment]
`/c` is an argument to the `cmd` program that tells it to run the string specified after it. It doesn't have to do with drive letters. FYI.

https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/cmd
