### ISSUE TITLE
"'gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded"

### ISSUE THREAD

**Issue by Razwerkz** [rfvgyhn/min-ed-launcher#103]
I am having trouble setting up min-ed-launcher to launch the [Flatpak version of EDMarketConnector](https://github.com/flathub/io.edcd.EDMarketConnector) on my Steam Deck (Arch Linux).  I have installed the Flatpak via the Discover Software Center, and it does function when launched manually.  But I am having trouble configuring the `settings.json` to launch it automatically.

[Here is the current configuration.](https://github.com/rfvgyhn/min-ed-launcher/files/11753533/settings.txt)  With these settings, the launcher can't seem to find EDMC, but the game launches normally, plays, and exits without either the game or the launcher crashing or hanging.  [Here's the log.](https://github.com/rfvgyhn/min-ed-launcher/files/11753576/min-ed-launcher.log)

**Comment by rfvgyhn** [comment]
Since you're wanting to launch a .desktop file, I think you'll have to use another tool like [dex](https://archlinux.org/packages/extra/any/dex/). Depending on what the .desktop file contains (I'm not familiar with flatpaks), you might just be able to use the `Exec=` value directly.

```json
{
    "fileName": "dex",
    "arguments": "/var/lib/flatpak/app/io.edcd.EDMarketConnector/current/active/export/share/applications/io.edcd.EDMarketConnector.desktop"
}
```

**Comment by Razwerkz** [comment]
I'm open to suggestions in regards to setup of the regular EDMC release.  I was having similar issues and had the thought that the Flatpak iteration would work more easily.

I'll try this out in the meantime, to see if it works well.  Will update here once I have done so.

**Comment by Razwerkz** [comment]
That didn't seem to work right away.  However, I later found out that my original problem came from trying to run EDMC out of Elite's prefix directory.  That being said, I got the regular release of EDMC to launch, but it doesn't seem to launch fully, as the window appears as a grey box with no contents, and the overlay does not work.

I have noticed this at each launch of min-ed-launcher:
`ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.`
Is this a possible cause?

**Comment by Razwerkz** [comment]
Nevermind, that seems to be a non-issue warning.  I think my remaining issues are with EDMCOverlay, so I'll move to the appropriate support avenue for that.  Thanks!

**Comment by dvdmuckle** [comment]
Necroing this issue to provide a fix for running the EDMC flatpak (and probably other flatpaks), this is the bit of configuration for running EDMC at launch, and notably, closing it at shutdown, that I use:
```json
	"processes": [
		{
			"filename": "/usr/bin/env",
			"arguments": "--unset LD_PRELOAD --unset LD_LIBRARY_PATH flatpak run -p io.edcd.EDMarketConnector"
		}
	],
	"shutdownProcesses": [
		{
			"filename": "/usr/bin/env",
			"arguments": "--unset LD_PRELOAD --unset LD_LIBRARY_PATH flatpak kill io.edcd.EDMarketConnector"
		}
	],
```
I'm not entirely sure if the `flatpak kill` is necessary, but most notably, unsetting `LD_PRELOAD` and crucially `LD_LIBRARY_PATH` makes the `flatpak` cli use the system libraries and not Steam's, and `-p` in the `flatpak run` command will make sure the flatpak quits when min-ed-launcher quits.

**Comment by Ambient-Impact** [comment]
@dvdmuckle Awesome, that works! Also, no, I don't think the `flatpak kill` is necessary because both EDMC and Observatory (running via Bottles) auto shut down for me without it.
