### ISSUE TITLE
MinEdLauncher crashes at "Cannot get required symbol SSL_set_alpn_protos from libssl"

### ISSUE THREAD

**Issue by hacktail** [rfvgyhn/min-ed-launcher#105]
**Describe the bug/error**
I am trying to run MinEdLauncher from steam on nixos 23.05, though I am facing a problem where the MinEdLauncher crashes because it's unable to get a require symbol, weirdly the log doesn't mention this error but the terminal that opens prints the error then instantly crashes.

**Debug log**

GE-Proton8-4

Screenshot captured by my quick hands right before the terminal exists:  
![Screenshot of the error](https://github.com/rfvgyhn/min-ed-launcher/assets/87021177/dba0cdb6-fbfe-4aec-8c63-a2ede1f6cf1b) 

The log:  
[min-ed-launcher.log](https://github.com/rfvgyhn/min-ed-launcher/files/11821894/min-ed-launcher.log)  

Steam launch args:  
alacritty -e ./MinEdLauncher %command% /autorun /autoquit /edo

**Comment by rfvgyhn** [comment]
After going through https://forums.gentoo.org/viewtopic-p-8750977.html?sid=0e9d1322083f844cd288eaff05f7374e and https://github.com/dotnet/runtime/issues/3239, I'm guessing there's a libssl package issue.

If you run `STEAM_COMPAT_DATA_PATH=/home/hacktail/Disku/SteamLibrary/steamapps/compatdata/359320 strace ./MinEdLauncher /dryrun 2>&1 | grep -e libssl -e libcrypto`, do you see any issues regarding libssl or libcrypto (e.g. `openat(AT_FDCWD, "/[path]/libssl.so.3", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)`?

Does specifying `CLR_OPENSSL_VERSION_OVERRIDE` (mentioned in previous links) change anything?
