### ISSUE TITLE
MinEdLauncher doesn't work since new launcher

### ISSUE THREAD

**Issue by arne-fuchs** [rfvgyhn/min-ed-launcher#106]
**Describe the bug/error**
MinEdLauncher just hangs up, since the new launcher has been released.

Startup parameters:

MANGOHUD=1 rxvt -e ./MinEdLauncher gamemoderun %command% /autorun /autoquit /edo

**Debug log**
2023-07-24 21:41:27.008 +02:00 [INF] Elite Dangerous: Minimal Launcher - v0.8.2+4646842b
2023-07-24 21:41:27.090 +02:00 [DBG] 
    Args: [|"gamemoderun"; "/home/arne/.local/share/Steam/ubuntu12_32/reaper";
  "SteamLaunch"; "AppId=359320"; "--";
  "/home/arne/.local/share/Steam/ubuntu12_32/steam-launch-wrapper"; "--";
  "/home/arne/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper/_v2-entry-point";
  "--verb=waitforexitandrun"; "--";
  "/home/arne/.local/share/Steam/compatibilitytools.d/GE-Proton8-9/proton";
  "waitforexitandrun";
  "/home/arne/.local/share/Steam/steamapps/common/Elite Dangerous/EDLaunch.exe";
  "/Steam"; "/novr"; "/autorun"; "/autoquit"; "/edo"|]
    OS: Linux64
    Env: STEAM_COMPAT_DATA_PATH=/home/arne/.local/share/Steam/steamapps/compatdata/359320
    
2023-07-24 21:41:27.092 +02:00 [DBG] Reading settings from '/home/arne/.config/min-ed-launcher/settings.json'
2023-07-24 21:41:27.251 +02:00 [DBG] Settings: { Platform = Steam
  DisplayMode = Pancake
  AutoRun = true
  AutoQuit = true
  WatchForCrashes = false
  ProductWhitelist = seq ["edo"]
  ForceLocal = true
  CompatTool =
   Some
     { EntryPoint = "gamemoderun"
       Args =
        [|"/home/arne/.local/share/Steam/ubuntu12_32/reaper"; "SteamLaunch";
          "AppId=359320"; "--";
          "/home/arne/.local/share/Steam/ubuntu12_32/steam-launch-wrapper"; "--";
          "/home/arne/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper/_v2-entry-point";
          "--verb=waitforexitandrun"; "--"; "python3";
          "/home/arne/.local/share/Steam/compatibilitytools.d/GE-Proton8-9/proton";
          "waitforexitandrun"|] }
  CbLauncherDir =
   "/home/arne/.local/share/Steam/steamapps/common/Elite Dangerous"
  PreferredLanguage = Some "en"
  ApiUri = https://api.zaonce.net/
  Restart = None
  AutoUpdate = true
  CheckForLauncherUpdates = true
  MaxConcurrentDownloads = 4
  ForceUpdate = set []
  Processes =
   [System.Diagnostics.ProcessStartInfo; System.Diagnostics.ProcessStartInfo]
  ShutdownProcesses = []
  FilterOverrides =
   seq [[FORC-FDEV-DO-1000, edo]; [FORC-FDEV-DO-38-IN-40, edh4]]
  AdditionalProducts = []
  DryRun = false }
2023-07-24 21:41:27.256 +02:00 [DBG] Unset LC_ALL. Using $LANG to determine correct UI culture
2023-07-24 21:41:27.283 +02:00 [INF] Elite Runtime
    Platform: Steam
    CobraBay Version: 1.7.6920.0
    Products Dir: /home/arne/.local/share/Steam/steamapps/common/Elite Dangerous/Products
2023-07-24 21:41:27.293 +02:00 [DBG] Getting machine id
2023-07-24 21:41:27.334 +02:00 [INF] Logging in
2023-07-24 21:41:27.335 +02:00 [DBG] Getting remote time

**Comment by rfvgyhn** [comment]
I'm unable to replicate the issue.

Does it just hang or does it crash? Is it always at `Getting remote time` or does it fail at other points too? Does a different version of proton change anything?

**Comment by arne-fuchs** [comment]
Nvm. I needed to restart whole pc, then it worked again. Thanks for the fast answer!
