### ISSUE TITLE
Launcher hangs instead of closing ED Exploration Buddy

### ISSUE THREAD

**Issue by Identifier** [rfvgyhn/min-ed-launcher#110]
It looks like the launcher can't figure out how to exit [Elite Dangerous Exploration Buddy](https://www.panostrede.de/EDEB/) when the Exploration Buddy's HUD window/overlay is up.  When Elite exits, the launcher closes EDMarketConnector and the Exploration Buddy's HUD window/overlay, but not the Exploration Buddy main window itself.

The launcher will hang here until the window is closed manually, then it will proceed. The log doesn't indicate one way or the other, only showing that (debug) the close was attempted, and (info) the program has been closed (once the program has been closed manually).

**Comment by rfvgyhn** [comment]
Sounds like EDEB doesn't respond to the terminate message/signal properly. The launcher will now force kill processes that don't shutdown after a configurable timeout.
