### ISSUE TITLE
Launcher doesn't seem to work in wine

### ISSUE THREAD

**Issue by Auratelience** [rfvgyhn/min-ed-launcher#116]
**Describe the bug/error**
Looking at the log it seems to be a JSON parsing error ("2023-12-09 11:02:37.898 +11:00 [ERR] Couldn't login: Couldn't parse json - ExpectedStartOfValueNotFound, < LineNumber: 0 | BytePositionInLine: 0.") followed by an html webpage of some sort.

This launcher was listed as a solution to running Elite Dangerous in Wine [here](https://www.reddit.com/r/macgaming/comments/14i71yq/comment/kcblawm/?utm_source=share&utm_medium=web2x&context=3) however I can't seem to get it to work.

Thank you!

**Debug log**
[min-ed-launcher.log](https://github.com/rfvgyhn/min-ed-launcher/files/13621854/min-ed-launcher.log)

**Comment by Auratelience** [comment]
Hmm. Maybe since the game hasn’t been opened normally. I will download a virtual machine since it launches well enough there, and then I will try again with the script in the virtual machine, then in wine. I’ll let you know how it goes.

thanks

**Comment by rfvgyhn** [comment]
Have you linked your steam account to your frontier account yet? That's something the normal launcher goes through that this one doesn't. You don't have to use the normal launcher though. You can do it through the web interface. https://www.frontierstore.net/frontier_partnerkeys/thirdparty/

**Comment by Auratelience** [comment]
Aha! No I have not done that. If I can do it through the web interface that’s great as I can save myself a windows installation. I’ll let you know how it goes.

**Comment by rfvgyhn** [comment]
If you purchased from steam after april 2019, you'll want to use the third party link/section. There should be a button in there that allows you to sign in with steam. Is that what you tried?

**Comment by Auratelience** [comment]
Yes I signed into steam on the website on the previous link you gave however it said no available keys were found. Sorry for turning you into tech support by the way haha. Feel free to just ditch me if you want.

**Comment by rfvgyhn** [comment]
Nah, no worries.

I have read that it can take more than 12 hours for frontier to acknowledge the license, though I don't know how true that is.

One of the issues with this game is that authentication problems aren't that uncommon. If it doesn't work after some time, I'd try the normal launcher. If that has issues, you might have to contact frontier support.

**Comment by Auratelience** [comment]
Yep will do.!” Thanks so much.

**Comment by Auratelience** [comment]
It seemed just waiting seemed to fix the login issue. The game seems to work for the most part. Just some weird resolution things. Thank you!
