### ISSUE TITLE
Unwanted automatic installation of additional products

### ISSUE THREAD

**Issue by Mystler** [rfvgyhn/min-ed-launcher#126]
I just updated to the latest release 0.10 of the min launcher and now it wants to install all of my not-installed product variants like the combat tutorial demo and the arena client. Probably legacy too but I quit the process before it got that far. I worked around it by disabling autoUpdate completely. However, this feels like an unintended regression.

**Comment by rfvgyhn** [comment]
Definitely unintended. Thanks for the report.

**Comment by Mystler** [comment]
Here you go
[min-ed-launcher.log](https://github.com/rfvgyhn/min-ed-launcher/files/15192258/min-ed-launcher.log)

**Comment by rfvgyhn** [comment]
Thanks. Looks like this is an issue specifically with Frontier logins. Until I push a fix, you'll need to keep auto update off or revert back to v0.9.0.

**Comment by rfvgyhn** [comment]
[CI Build](https://github.com/rfvgyhn/min-ed-launcher/actions/runs/8933166188) should have the fix for this. Let me know if it doesn't work.

**Comment by Mystler** [comment]
Seems to work well, thanks for the fast response!
