### ISSUE TITLE
Argument to restart additional processes when /restart is used

### ISSUE THREAD

**Issue by leonardofelin** [rfvgyhn/min-ed-launcher#129]
I run 3dmigoto as a separate process in order to get EDHM_UI and OpenComposite for VR working together.
3dmigoto needs to launch before the game every time.

Using the /restart option, the game launches after closing, but the "processes" list doesn't get relaunched - which makes sense for most of the third-party applications that we run with the game.

What I'd like to ask is to have and additional option in the processes that would relaunch that process together with the game. Something like:
```
     "fileName": "E:\\3Dmigoto\\3DMigoto Loader.exe",
     "arguments": "",
     "restart": true
```

Thank you for your time!

**Comment by rfvgyhn** [comment]
Feature added. Use `"restartOnRelaunch": true`. You can use the [CI build](https://github.com/rfvgyhn/min-ed-launcher/actions/runs/9358160599) until the next release.

**Comment by leonardofelin** [comment]
Hi, just tested it and worked perfectly. Thank you so much!
