### ISSUE TITLE
[Linux][Proton >= 5.13] pressure-vessel uses different number of arguments

### ISSUE THREAD

**Issue by kerberizer** [Rfvgyhn/min-ed-launcher#13]
While trying to test #6, I hit another problem that seems introduced by some recent updates to either Steam or pressure-vessel itself: pressure-vessel is started with fewer arguments which, apparently, breaks the detection of `cbLaunchDir` [here](https://github.com/Rfvgyhn/min-ed-launcher/blob/de0ad1d62c5b28a8dc82335baf5135f0d4088697/src/MinEdLauncher/Settings.fs#L25).

Comparing to [your tests](https://github.com/Rfvgyhn/min-ed-launcher/blob/de0ad1d/tests/Settings.fs#L105), the arguments `--deploy=soldier` and `--suite=soldier` seem to not be used anymore. Here are the logs from Proton 5.13 and Experimental. Just to be sure I also tested with both Steam Beta and the stable version.

```
2021-03-20 16:26:48.521 +02:00 [DBG] Args: [|"/home/+redacted+/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point";
  "--verb=waitforexitandrun"; "--";
  "/home/+redacted+/.local/share/Steam/steamapps/common/Proton 5.13/proton";
  "waitforexitandrun";
  "/home/+redacted+/.local/share/Steam/steamapps/common/Elite Dangerous/EDLaunch.exe";
  "/Steam"; "/novr"; "/autoquit"; "/EDH"|]
2021-03-20 16:26:48.628 +02:00 [DBG] Reading settings from '/home/+redacted+/.config/min-ed-launcher/settings.json'
2021-03-20 16:26:48.959 +02:00 [DBG] Settings: Ok
  { Platform = Dev
    DisplayMode = Pancake
    AutoRun = false
    AutoQuit = true
    WatchForCrashes = false
    ProductWhitelist = set ["edh"]
    ForceLocal = false
    Proton =
            Some
              { EntryPoint =
                            "/home/+redacted+/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point"
                Args =
                      [|"--verb=waitforexitandrun"; "--";
                        "/home/+redacted+/.local/share/Steam/steamapps/common/Proton 5.13/proton";
                        "waitforexitandrun"; "python3";
                        "/home/+redacted+/.local/share/Steam/steamapps/common/Elite Dangerous/EDLaunch.exe";
                        "/Steam"|] }
    CbLauncherDir = "/"
    PreferredLanguage = None
    ApiUri = https://api.zaonce.net/
    Restart = (false, 3000L)
    Processes = [] }
2021-03-20 16:26:48.968 +02:00 [ERR] Unable to get version: Unable to find CBViewModel.dll in directory /
```

```
2021-03-20 16:31:25.774 +02:00 [DBG] Args: [|"/home/+redacted+/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point";
  "--verb=waitforexitandrun"; "--";
  "/home/+redacted+/.local/share/Steam/steamapps/common/Proton - Experimental/proton";
  "waitforexitandrun";
  "/home/+redacted+/.local/share/Steam/steamapps/common/Elite Dangerous/EDLaunch.exe";
  "/Steam"; "/novr"; "/autoquit"; "/EDH"|]
2021-03-20 16:31:25.864 +02:00 [DBG] Reading settings from '/home/+redacted+/.config/min-ed-launcher/settings.json'
2021-03-20 16:31:26.249 +02:00 [DBG] Settings: Ok
  { Platform = Dev
    DisplayMode = Pancake
    AutoRun = false
    AutoQuit = true
    WatchForCrashes = false
    ProductWhitelist = set ["edh"]
    ForceLocal = false
    Proton =
            Some
              { EntryPoint =
                            "/home/+redacted+/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point"
                Args =
                      [|"--verb=waitforexitandrun"; "--";
                        "/home/+redacted+/.local/share/Steam/steamapps/common/Proton - Experimental/proton";
                        "waitforexitandrun"; "python3";
                        "/home/+redacted+/.local/share/Steam/steamapps/common/Elite Dangerous/EDLaunch.exe";
                        "/Steam"|] }
    CbLauncherDir = "/"
    PreferredLanguage = None
    ApiUri = https://api.zaonce.net/
    Restart = (false, 3000L)
    Processes = [] }
2021-03-20 16:31:26.257 +02:00 [ERR] Unable to get version: Unable to find CBViewModel.dll in directory /
```

I'm sorry that I can't contribute directly a patch, but it's the first time I look at F# code. One general idea that comes to my mind—and most likely you've thought about it yourself—is to have a more flexible matching. I don't know if this would make sense: if our initial assumption of where `EDLaunch.exe` should be located in the arguments array (say, `arr[n]`) fails, to try also, as sort of a fallback, regex matching the launcher in the neighbouring 2-3 arguments (`arr[n-2]..arr[n+2]`). This seems to me like a way to avoid having to constantly adjust the expected number of arguments if they continue changing in the future. But maybe this doesn't make sense at all—again, I'm afraid I don't have the knowledge to understand well your code—so feel free to just ignore this.

Last but not least, thank you very much for the time and effort to create and maintain this wonderful project!

**Comment by Rfvgyhn** [comment]
Thanks for the depth. I've pushed a fix to both branches that should handle any number of soldier arguments going forward.

Updated binaries for [master](https://github.com/Rfvgyhn/min-ed-launcher/actions/runs/672029184) and [frontier-auth](https://github.com/Rfvgyhn/min-ed-launcher/actions/runs/672047072) can be downloaded from CI builds.
