### ISSUE TITLE
Apllications not quitting on game exit

### ISSUE THREAD

**Issue by icescoop12** [rfvgyhn/min-ed-launcher#134]
I'm running via steam all seems okay 
Apart from the applications don't close  after game quits?
here is my entrance in steam libary:
![image](https://github.com/user-attachments/assets/fdf2e45c-09f3-4640-8e8b-6d95359e0f39)

here is my log:
[min-ed-launcher.log](https://github.com/user-attachments/files/16487999/min-ed-launcher.log)

**Comment by rfvgyhn** [comment]
Does the same problem occur if you remove EDCopilot from your settings file?

**Comment by rfvgyhn** [comment]
Did you figure something out or are you still having issues?

**Comment by icescoop12** [comment]
fixed issue ,was settings file
