### ISSUE TITLE
Add setting to override env-vars

### ISSUE THREAD

**Issue by kafeg** [rfvgyhn/min-ed-launcher#19]
Please add possibility to overrride env vars for the game.

For e.g. i want to override %USER% to split CMDR journals from Steam and Epic game accounts.

**Comment by Ejsstiil** [comment]
This folder maps game itself not launcher. Make necessary steps in your script, eq. swap folders before launch

**Comment by rfvgyhn** [comment]
As mentioned in https://github.com/rfvgyhn/min-ed-launcher/issues/69#issuecomment-1292778672, you can use `runas` to separate special env vars like %USER%.
