### ISSUE TITLE
Not finding my settings.json file

### ISSUE THREAD

**Issue by VMSrefugee** [Rfvgyhn/min-ed-launcher#2]
Loving the new minimal launcher!

I wanted to try the auto-restart, but it's not seeing my .json file, according to the value of "restart" that gets logged.  My %LOCALAPPDATA%\min-ed-launcher\settings.json is:

`{
    "restart": {
        "enabled": true,
        "shutdownTimeout": 3
    }
}`
Would it be possible to log the actual filename of the settings file it opens (or tries to)?

Thanks!

**Comment by Rfvgyhn** [comment]
Well, on Windows, it looks like the settings file is being created in `%LOCALAPPDATA%\elite-dangerous-launcher` instead of `%LOCALAPPDATA%\min-ed-launcher`. The temporary workaround is to use that location until I can figure out why it's doing that.

**Comment by Rfvgyhn** [comment]
It seems to be fixed though I don't know why. Perhaps some sort of caching issue with the automated release build. I've setup a CI build, without changing anything related where it reads the settings file, and it now reads from min-ed-launcher.

Can you try the [latest CI build](https://github.com/Rfvgyhn/min-ed-launcher/actions/runs/407255847) and see if it reads from the correct directory?

**Comment by VMSrefugee** [comment]
The log line made it easy to see the problem, thanks!  (My %LOCALAPPDATA% (according to the search box in the toolbar) is `C:\Users\VMSrefugee\AppData`, but it's looking in `C:\Users\Scott\AppData\Local\min-ed-launcher\settings.json`.  Which is a more logical place for it, and I'm sure there's a reason it told me something else, and everyone apparently knows it just lies about that?  Not a PC guy, obv.  Thanks for the help!)

**Comment by Rfvgyhn** [comment]
Interesting. I haven't seen %LOCALAPPDATA% point to the root app data folder before. Glad it's working for you now. Thanks for the idea of logging the settings path.
