### ISSUE TITLE
Can't pre-launch EDMarket Connector (Access denied; Win10)

### ISSUE THREAD

**Issue by DocMinus** [Rfvgyhn/min-ed-launcher#20]
What am I doing wrong? Win10, Steam Version (Epic not tested)
Running the script works, but can't start another app. I wanted to include EDMC (and eventually Voice Attack).

The script throws following error:
_Unable to start pre-launch process C:\Program Files (x86)\EDMarketConnector
System.ComponentModel.Win32Exception (5): Access is denied._
My Json looks like this:
```
{
    "apiUri": "https://api.zaonce.net",
    "watchForCrashes": false,
    "language": null,
    "restart": {
        "enabled": false,
        "shutdownTimeout": 3
    },
    "processes": [
        {
             "fileName": "C:\\Program Files (x86)\\EDMarketConnector"
        }
    ]
}
```
(Do I understand correctly, one only writes the path, not the app in fileName? I tried that anyway, but then the script just crashes, i.e. writing "fileName": "C:\\Program Files (x86)\\EDMarketConnector\\EDMarketConnector.exe")

**Comment by Rfvgyhn** [comment]
It should be the full path to the executable. `"fileName": "C:\\Program Files (x86)\\EDMarketConnector\\EDMarketConnector.exe"`

When you provide the full path and it crashes, do you get any output in the log file? If so, can you post that?

**Comment by DocMinus** [comment]
Thanks. It works now!?
Odd. Maybe a type on my side? Or a rebooting the machine today.
So we can just can close this. 
Sorry about that. And thanks for the tool!
