### ISSUE TITLE
 Can't pre-launch EDMarket Connector (issues setting file name directory in Linux 

### ISSUE THREAD

**Issue by Eeyoresyndrome** [Rfvgyhn/min-ed-launcher#23]
```
"processes": [
        {
        "fileName": "home/username/Desktop/EDMarketConnector-Release-4.2.7/EDMarketConnector.py",
        }
                ]
}
```
This is what my current setup looks like and its launching the game just fine with the konsole launch command. 

But I am having the slight issue of not being sure if I have it set to the right directory to launch EDMC.... It launches  when I load it manually just fine so I know it is setup correctly.

**Comment by Rfvgyhn** [comment]
Maybe the missing `/` is a typo, but your absolute path needs to begin with a forward slash. You'll also want to remove the trailing comma.

```json
"processes": [
    {
        "fileName": "/home/username/Desktop/EDMarketConnector-Release-4.2.7/EDMarketConnector.py"
    }
 ]
```

**Comment by Eeyoresyndrome** [comment]
Silly me, that fixed it, thank you.
