### ISSUE TITLE
Error launch egs 

### ISSUE THREAD

**Issue by Weedmanov** [Rfvgyhn/min-ed-launcher#24]
I am using the latest version of EGS.
Windows 10.
Elite dangerous latest version too.
I did everything according to the instructions for EGS, but on startup it gives an error: check the installation files.
also stopped starting EDMC. how to solve these problems? 
Also, I forgot to mention the 3 launch parameters, they are exposed in the launcher.
I used the bootstrapper from the 3.0 release

**Comment by Rfvgyhn** [comment]
Does the Epic client give that error or does Elite Dangerous give that error? You might need to verify your game files within the Epic client. It may also help if you post the contents of your log file. `logs/min-ed-launcher.log`

**Comment by Weedmanov** [comment]
That error is active than I launch ED from EGS client or launch it from desktop.  
the log file will be a little later

**Comment by Weedmanov** [comment]
So, the log file with using your launcher is :
