### ISSUE TITLE
HTTP 500 after relasing first update for Odyssey

### ISSUE THREAD

**Issue by MGM175** [Rfvgyhn/min-ed-launcher#27]
So I've tried to launch the game via launcher, but ended with error 500.

`[18:23:52 INF] Elite Dangerous - Minimal Launcher
Platform: Steam
OS: Win64
CobraBay Version: 0.4.6709.0
Launcher Version: 0.4.0
Products Dir: C:\Program Files (x86)\Steam\steamapps\common\Elite Dangerous\Products
[18:23:53 ERR] Couldn't login: 500: Internal Server Error
`

Also, after doing a log-in via original launcher, when attempted to log in again via Minimal Launcher, I also got HTTP 500.

Can't replicate right now, because I'm doing the Odyssey upgrade.

**Comment by Rfvgyhn** [comment]
An http 500 usually means FDev's server errored out. If you're unable to get passed it after multiple attempts with some time in-between, can you post a full log entry?

**Comment by Rfvgyhn** [comment]
It looks like it's a [known issue](https://twitter.com/EliteDangerous/status/1397953826519388161). They said [it's been fixed](https://twitter.com/EliteDangerous/status/1397973872125882369), but some users are saying they are still getting 500 errors. Once this is resolved on their end and if you still see these errors, feel free to re-open this issue.
