### ISSUE TITLE
(Feature request) Configurable cache folder

### ISSUE THREAD

**Issue by llorephie** [Rfvgyhn/min-ed-launcher#34]
Cache (download) folder by default hosts on %LOCALAPPDATA% (Windows) or $XDG_CONFIG_HOME (Linux), which is in most cases located on system drive, which can be small-sized in some cases :)

Can you add command-line/config switch for cache folder?

Btw, usage $XDG_CONFIG_HOME for download cache on linux is in some way incorrect, according to XDG specs: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html , more suitable are $XDG_CACHE_HOME or $XDG_DATA_HOME

**Comment by Rfvgyhn** [comment]
Are cached files being written to `$XDG_CONFIG_HOME` for you? If so, that's a bug as cache files are [supposed](https://github.com/Rfvgyhn/min-ed-launcher/blob/ba56428036ae9b58bba1946694b6c269a4e7c444/src/MinEdLauncher/Extensions.fs#L485-L495) to be written to `$XDG_CACHE_HOME` and fallback to `~/.cache` if `$XDG_CACHE_HOME` isn't specified.

**Comment by llorephie** [comment]
> Are cached files being written to `$XDG_CONFIG_HOME` for you? If so, that's a bug as cache files are [supposed](https://github.com/Rfvgyhn/min-ed-launcher/blob/ba56428036ae9b58bba1946694b6c269a4e7c444/src/MinEdLauncher/Extensions.fs#L485-L495) to be written to `$XDG_CACHE_HOME` and fallback to `~/.cache` if `$XDG_CACHE_HOME` isn't specified.

Re-checked - you are right here, on linux it goes where it should via envinroment, seems like that machine was affected by 386ds overrides (roaming profile), thanks :)
