### ISSUE TITLE
Broke after update 7 !!!!!!!!!

### ISSUE THREAD

**Issue by PyronoxO** [Rfvgyhn/min-ed-launcher#39]
First and foremost i would like to thank you for the great  work you have done with this launcher it's a life saver.

PLLLLLLLLEase update to work after the new update as the original launcher sucks !!!!!!

**Comment by PyronoxO** [comment]
sure here its 

021-09-12 02:26:39.067 +04:00 [INF] Elite Dangerous: Minimal Launcher - v0.5.3
2021-09-12 02:26:39.152 +04:00 [DBG] 
    Args: [||]
    OS: Win64
    
2021-09-12 02:26:39.165 +04:00 [DBG] Reading settings from 'C:\Users\ponto.DESKTOP-SNTQMLB\AppData\Local\min-ed-launcher\settings.json'
2021-09-12 02:26:39.369 +04:00 [DBG] Settings: Error "Unknown platform. Failed to find Elite Dangerous install directory"
2021-09-12 02:26:39.369 +04:00 [ERR] Unknown platform. Failed to find Elite Dangerous install directory

**Comment by Rfvgyhn** [comment]
It looks like you are trying to run it directly (`Args` array is empty). Did you follow the [Setup](https://github.com/Rfvgyhn/min-ed-launcher#setup) steps for your desired platform?

**Comment by PyronoxO** [comment]
`yes of course it was running just fine before update 7
after the update it stopped and i was getting this message

**Comment by Rfvgyhn** [comment]
Is this Steam, Epic or a regular Frontier account? Can you show me what your launcher options/shortcut looks like?

**Comment by PyronoxO** [comment]
steam

**Comment by PyronoxO** [comment]
in my case its actually  cmd /f "MinEdLauncher.exe %command% /autorun /restart 5 /EDO"

as i don't have my steam path in C

**Comment by Rfvgyhn** [comment]
`/h` should be `/c`. That particular option doesn't refer to the disk letter but tells `cmd` to run the subsequent command.

**Comment by PyronoxO** [comment]
ahh ok  thanx for the clarification,  let me try that
