### ISSUE TITLE
SteamVR supported?

### ISSUE THREAD

**Issue by ri0t** [rfvgyhn/min-ed-launcher#41]
Hello and thanks for this great launcher - it enables me to use a controller again, since that (weirdly) only works with Proton >6.18 on my machine, which Frontier's launcher apparently dislikes, maximally.

Sadly, when i try to launch ED via SteamVR, it doesn't really start, which it does when using an older (controller breaking) Proton.

Maybe this weird behaviour is related: When i launch ED (with or w/o SteamVR), I get some hung wine-processes, which i need to kill immediately. Only then it proceeds to launch the min-ed-launcher.

**Comment by rfvgyhn** [comment]
Closing because of no feedback. Feel free to reopen it if you are still having issues.
