### ISSUE TITLE
Opening on Steam bypasses controller integration

### ISSUE THREAD

**Issue by SunlightSocial** [rfvgyhn/min-ed-launcher#46]
Installed this mod and am very impressed by the speed, so I'm hoping to get this fixed/answered.

I've got it working on Steam however it will refuse to recognise any Xbox controller input. It seems to bypass steam controller activation. Is there any way to fix this?

**Comment by pan-mroku** [comment]
Try connecting the controller after the game window appears.

*Od: *SunlightSocial ***@***.***>
*Do: *rfvgyhn/min-ed-launcher ***@***.***>
*DW: *Subscribed ***@***.***>
*Data: *16 lut 2022 14:15:22
*Temat: *[rfvgyhn/min-ed-launcher] Opening on Steam bypasses controller integration (Issue #46)

**Comment by SunlightSocial** [comment]
> Try connecting the controller after the game window appears.

Unfortunately that did not seem to work. I do however have it working on Epic (although the load up time is a bit slower). I think it's because steam has to open the default way to activate it's steam controller business, but I'm not sure because I'm not that clever.

**Comment by SunlightSocial** [comment]
Going into Big Picture mode and ensuring the game runs with steam controller input "Forced Off" fixed this issue.

Thank you for your wonderful product :)
