### ISSUE TITLE
Cannot launch from Steam: Exec format error (Proton-GE)

### ISSUE THREAD

**Issue by xolophreny** [Rfvgyhn/min-ed-launcher#5]
Steam commandline: `sakura -x "./MinEdLauncher %command%`
Output:
```
ERROR: ld.so: object '/home/xolophreny/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
[19:45:18 INF] Elite Dangerous - Minimal Launcher
Platform: Steam
OS: Linux64
CobraBay Version: 0.4.6600.0
Launcher Version: 0.3.0
Products Dir: /home/xolophreny/.steam/steam/steamapps/common/Elite Dangerous/Products
[S_API] SteamAPI_Init(): Loaded '/home/xolophreny/.local/share/Steam/linux64/steamclient.so' OK.
Setting breakpad minidump AppID = 359320
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198093965286 [API loaded no]
[19:45:21 INF] Logged in via Steam as: Dan Khar
[19:45:22 INF] Checking for updates
[19:45:23 INF] Available Products:
	(Elite Dangerous: Horizons, Up to date)
	(Elite Dangerous, Up to date)
	(Elite Dangerous: Arena, Up to date)
	(Single Player Combat Training, Up to date)
[19:45:24 ERR] Couldn't start selected product: System.ComponentModel.Win32Exception (8): Exec format error
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at MinEdLauncher.Product.run$cont@132(FSharpOption`1 proton, String args, RunnableProduct product, Unit unitVar)
Press any key to quit...
```

Couldn't get the launcher to find game directory without Steam (using a config file at `/home/xolophreny/.config/min-ed-launcher/settings.json`), so yet to try that

**Comment by xolophreny** [comment]
That only occurs with Proton-GE, regular Proton actually works

**Comment by Rfvgyhn** [comment]
I'll download Proton-GE and see if I can reproduce it.

**Comment by Rfvgyhn** [comment]
Hmm, Proton-GE 5.21-GE-1 is working for me.

* Were you using proton 5.0 or 5.13/experimental when you got it to run? If 5.0, can you try 5.13 and see if you get the same error?
* Which version of Proton-GE are you using?
* Do any other games of yours work with Proton-GE
* Are you using steam-runtime or steam-native?

**Comment by xolophreny** [comment]
Aha, yeah, I was using slightly outdated Proton-5.9-GE-8-ST because the newer ones are based on 5.13 and that still has issues with overlays like vkBasalt. Also I think it's steam-runtime, and other games work as expected.

Tested some other Proton versions:

- 5.21-GE-1: Launcher works, vkBasalt almost works but not quite there, the game crashes as soon as it finishes loading and tries to connect to server. Launcher with /autoquit doesn't notice that and continues to run, does it need watchForCrashes for that?
- 5.13: Launcher works, vkBasalt almost works, game seems to behave normally without crashing.
- 5.9-GE-8-ST: Above error.
- 5.0: Everything seems to work fine.

Then it's a debate between weird vkBasalt behaviour, vanilla launcher or older Proton. Weird

**Comment by Rfvgyhn** [comment]
`watchForCrashes` launches the game via `WatchDog64.exe` like how the default launcher does. Enabling that shouldn't change anything.

When you use vkBasalt + 5.21-GE-1 and after it crashes, do you have lingering `pressure-vessel` processes running? The launcher starts proton which starts pressure-vessel and finally the game. I'm guessing the game crashes but pressure-vessel doesn't properly notice and doesn't stop which the the launcher won't be able to fix.

I tested 5.9-GE-8-ST and initially got the _Failed to find Elite Dangerous install directory_ error. I added support for proton when it's in the `compatibilitytools.d` dir. My game ran as expected after that though. From what I've read about `Exec format error`, my guess is there's some sort of environment issue. It looks like that error pops up when either a process isn't run on the correct platform (e.g. 32bit and 64bit, arm and x86, etc...) or a script is missing a shebang. I don't know if there's an issue on your end that breaks things or if there's something specific on my machine that makes it work.

**Comment by xolophreny** [comment]
Yes, got `pressure-vessel-launcher` and other processes still running after crash. Alright, that explains it.
Probably some issues on my end, had some shenanigans when Proton 5.13 just released but didn't ship its runtime properly. Might be something there.

In other news - with latest commit the `Exec format error` no longer occurs on 5.9-GE and both the launcher and the game work as expected. Thanks!
