### ISSUE TITLE
Feature Request: Shutdown/Cleanup commands

### ISSUE THREAD

**Issue by mdmallardi** [rfvgyhn/min-ed-launcher#50]
Just as we currently can execute processes on the startup of the launcher, I would love it if we could define processes to execute as the launcher is shut down.

My use case is to utilize both a shutdown and a startup script to keep a remote copy of my VisitedStarCache synced between the different systems I would like to play Elite with since FDev won't keep that on their servers.

Thanks for your time and consideration.

**Comment by slippycheeze** [comment]
I'd also find this useful.  I currently use Playnite, a "game launcher", which offers the same feature to do this – but I'm stuck with powershell scripts running in-process, or doing nasty things, to make this work.    Be very nice to have something in the launcher instead.

**Comment by pilgerone** [comment]
This would be useful to turn some stuff off at the end of a play session, like, for example, shutting down SteamVR and disabling joysticks devices so they don't interfere with Windows' sleep mode. It can also be used to sync game data, etc.

I tried a workaround to have one of the processes to monitor for a quit message and do some wrapping-up, but it appears that min-ed is quite aggressive when shutting everything down.

**Comment by rfvgyhn** [comment]
Added in cebed90

**Comment by mdmallardi** [comment]
Thanks for this! I can't wait to cut out all the steps I currently have in order to run the game!
