### ISSUE TITLE
Unable to activate MangoHud

### ISSUE THREAD

**Issue by arne-fuchs** [rfvgyhn/min-ed-launcher#51]
I am trying to enable MangoHud with following Launch Options in Steam:
`MANGOHUD=1 gnome-terminal -- ./MinEdLauncher  %command%`
sadly it has no effect.

It would be nice to define env. options in the config.

Running on linux

**Comment by rfvgyhn** [comment]
When you say has no effect, you mean that mango hud doesn't appear and not the game doesn't launch, right?

If the former, I'm not able to replicate this issue. Does mango hud appear if you don't use the min launcher (e.g. `MANGOHUD=1 %command%`)? Does it work if you globally enable mango hud (setting the var in `/etc/environment`)? 

If the latter, can you post the contents of your log file?

**Comment by arne-fuchs** [comment]
I reinstalled mangohud with their installer on github and not with apt. It does work no. Sorry for bothering you.
But thanks for the great work! Really love your launcher.
