### ISSUE TITLE
"No selected product" when running 0.6.0 with /edh4 switch on Linux/Steam

### ISSUE THREAD

**Issue by jonathanrwatts** [rfvgyhn/min-ed-launcher#57]
I'm running Elite Dangerous through Steam on a Kubuntu 22.04 Linux environment.  I own Horizons, but not Odyssey.  Min-ed-launcher v0.5.4 (IIRC) was working fine with the `/edh` switch.

Just downloaded v0.6.0+8103a3a6, and made sure my Steam installation was up to date, and also deleted the `settings.json` file from `~/.config/min-ed-launcher`.

When I use the `/edh` switch, the games loads, but on version 3.8.  If I try the `/edh4` switch instead, I get a `No selected project` error.  I also tried both switches (`/edh /edh4`), but that just ran 3.8 again.  If I leave out `/autorun`, I only get base ED, ED:H, or ED:A options (no ED:H 4.0), and the ED:H option runs 3.8 again.

I can't run the Frontier ED launcher, as it crashes and freezes immediately on my system.

Edit:  Forgot to mention I'm using Proton 7.0-4, which I believe is the latest non-experimental version.

**Comment by jonathanrwatts** [comment]
Just found the log file at `~/.local/.state/min-ed-launcher.log`, this line appears to be the culprit:
`2022-09-17 23:34:40.564 -06:00 [DBG] Disabling 'Elite Dangerous: Horizons (4.0)'. Unable to find product at '/home/jonathan/.local/share/Steam/steamapps/common/Elite Dangerous/Products/FORC-FDEV-DO-38-IN-40/VersionInfo.txt'`

Sure enough, there is no `FORC-FDEV-DO-38-IN-40` directory under the `Products` directory.  Not sure how to proceed from here....

**Comment by jonathanrwatts** [comment]
Never mind, I was able to determine what the problem was and fix it.  For anyone else with the same issue, I did not realize you have to install Horizons 4.0 from the Frontier ED Launcher before you can use it.  I was able to get the Frontier launcher working by editing the `EDLaunch.exe.config` file in `~/.local/share/Steam/steamapps/common/Elite Dangerous/` and changing the setting for `DXCheck` to `False`.

**Comment by rfvgyhn** [comment]
For future reference, #54 covers how to install 4.0 without the default launcher.
