### ISSUE TITLE
Feature request: Support launching Horizons in 4.0 mode for Odyssey accounts

### ISSUE THREAD

**Issue by Xeeke** [rfvgyhn/min-ed-launcher#58]
If you own Odyssey the available products list excludes Horizons 4.0, but it's actually still available by appending "SeasonTwo" as a command line argument to EliteDangerous64.exe when launching the Odyssey client.

`"C:\Program Files (x86)\Steam\steamapps\common\Elite Dangerous\Products\elite-dangerous-odyssey-64\EliteDangerous64.exe" "wseed 00000"   "ServerToken bigtokenhere " /language English\\UK SeasonTwo`

This would be extremely useful in order for players to be able to instance together on the new codebase and participate in 4.0 content even if not everyone in a group has Odyssey.

**Comment by rfvgyhn** [comment]
Since I don't have Odyssey, can you confirm for me that the authorized products response doesn't contain an object with `product_sku` = `FORC-FDEV-DO-38-IN-40`? This would be in the log file after `[DBG] Purchases Response:`

```
{
    "colour": "#f07b05",
    "filter": "ed",
    "directory": "elite-dangerous-odyssey-64",
    "serverargs": "",
    "gameargs": "SeasonTwo",
    "sortkey": "04",
    "product_name": "Elite Dangerous: Horizons (4.0)",
    "product_sku": "FORC-FDEV-DO-38-IN-40",
    "template": "http://hosting.zaonce.net/launcher-steam/elite/en.html"
}
```

**Comment by Xeeke** [comment]
Confirmed, no such product listed. The following is the list of products that comes up for an account which owns Odyssey.

```
[INF] Available Products:
	Elite Dangerous: Odyssey  FORC-FDEV-DO-1000 Up to Date
	Elite Dangerous: Horizons FORC-FDEV-D-1013  Up to Date
	Elite Dangerous           FORC-FDEV-D-1010  Up to Date
	Elite Dangerous: Arena    FORC-FDEV-D-1012  Up to Date
```

Rather than being a separate sku, the Odyssey sku will just start as Horizons 4.0 if launched with the SeasonTwo argument.

**Comment by Xeeke** [comment]
The full response from the log-

```
[DBG] Purchases Response:
{"purchases":[
{
	"colour":"#f07b05",
	"filter":"ed",
	"directory":"elite-dangerous-64",
	"serverargs":"",
	"gameargs":"SeasonOne",
	"sortkey":"06",
	"product_name":"Elite Dangerous",
	"product_sku":"FORC-FDEV-D-1010",
	"template":"http://hosting.zaonce.net/launcher/elite/en.html"
},
{
	"colour":"#f07b05",
	"filter":"eda",
	"directory":"elite-dangerous-64",
	"serverargs":"",
	"gameargs":"CQCArena",
	"sortkey":"20",
	"product_name":"Elite Dangerous: Arena",
	"product_sku":"FORC-FDEV-D-1012",
	"template":"http://hosting.zaonce.net/launcher/elite-dangerous-arena/en.html"
},
{
	"colour":"#f07b05",
	"filter":"ed",
	"directory":"COMBAT_TUTORIAL_DEMO",
	"serverargs":"",
	"gameargs":"",
	"sortkey":"30",
	"product_name":"Single Player Combat Training",
	"product_sku":"COMBAT_TUTORIAL_DEMO",
	"template":"http://hosting.zaonce.net/launcher/elite/en.html"
},
{
	"colour":"#0a8bd6",
	"filter":"edh",
	"directory":"elite-dangerous-64",
	"serverargs":"",
	"gameargs":"",
	"sortkey":"05",
	"product_name":"Elite Dangerous: Horizons",
	"product_sku":"FORC-FDEV-D-1013",
	"template":"http://hosting.zaonce.net/launcher/elite-dangerous-horizons/en.html"
},
{
	"colour":"#0a8bd6",
	"filter":"edh",
	"directory":"elite-dangerous-odyssey-64",
	"serverargs":"",
	"gameargs":"",
	"sortkey":"00",
	"product_name":"Elite Dangerous: Odyssey",
	"product_sku":"FORC-FDEV-DO-1000",
	"template":"http://hosting.zaonce.net/launcher/odyssey/en.html"
}
]}
```

**Comment by rfvgyhn** [comment]
So I think this should work now. Can you download the [CI build](https://github.com/rfvgyhn/min-ed-launcher/actions/runs/3094774362) and let me know if it works.

 You'll need to update your `settings.json` file to include 
```json
"additionalProducts": [{
    "filter": "edh4",
    "directory": "elite-dangerous-odyssey-64",
    "serverargs": "",
    "gameargs": "SeasonTwo",
    "sortkey": "04",
    "product_name": "Elite Dangerous: Horizons (4.0)",
    "product_sku": "FORC-FDEV-DO-38-IN-40"
}]
```

If you want the `/edo` flag to still work, you won't be able to use the Odyssey SKU since the `/edh4` flag would be overwritten by the `filterOverrides` settings. Unfortunately, FDev is still returning `edh` for Odyssey.

**Comment by Xeeke** [comment]
That works. With the new build and settings update it launched /edh4 and successfully ran Horizons 4.0.

![EDO-EDH4 launch](https://user-images.githubusercontent.com/13757474/191408639-c0884260-79b2-4104-a2d7-f8ab763d2809.jpg)

**Comment by rfvgyhn** [comment]
Cool. I should have a new release shortly that includes this.
