### ISSUE TITLE
Version Switches Do Not All Work: /ed, /edh, /edo

### ISSUE THREAD

**Issue by ZekeWolf** [rfvgyhn/min-ed-launcher#62]
This is a great utility and solves a good handful of problems when launching the game. 

However, the version swtcthes do not seem to work as intended. Here is what happens. I am running the 0.71 version of MinEdLauncher. I am running the game through Steam, with the following  basic command line parameters in 'Properties | General | Launch Options':

cmd /c "MinEdLauncher.exe %command% /autorun /autoquit"

When I run this with the /ed switch, it runs base Elite Dangerous, neither Horizons nor Odyssey, as expected

But when I run this with the /edh switch, it runs Odyssey. 

And when I run this with the /edo switch, it fails: the CMD box appears then autoquits. 

I attach separate log files that result from using the /edh and /edo switch.

I am sure it's something I am missing. Please advise any changes I need to make. And thank you for your work on this.

[min-ed-launcher (for edh switch).log](https://github.com/rfvgyhn/min-ed-launcher/files/9643384/min-ed-launcher.for.edh.switch.log)
[min-ed-launcher (for edo switch).log](https://github.com/rfvgyhn/min-ed-launcher/files/9643387/min-ed-launcher.for.edo.switch.log)

**Comment by rfvgyhn** [comment]
Does your [settings file](https://github.com/rfvgyhn/min-ed-launcher#settings) have any values for `filterOverrides`? It should come with `{ "sku": "FORC-FDEV-DO-1000", "filter": "edo" }` if you've never run the launcher before. If it's not there, try adding it.

**Comment by ZekeWolf** [comment]
Thank you for the quick response. I am not sure of the syntax to use for the insertion you suggested in the setting.json file. [I am not familiar with this particular language format.] I did have a settings file. Here is the text it contained: 

{
    "apiUri": "https://api.zaonce.net",
    "watchForCrashes": false,
    "language": null,
    "restart": {
        "enabled": false,
        "shutdownTimeout": 3
    },
    "autoUpdate": true,
    "maxConcurrentDownloads": 4,
    "forceUpdate": "",
    "processes": []
}

Here is the way that I have inserted the text:

{
    "apiUri": "https://api.zaonce.net",
    "watchForCrashes": false,
    "language": null,
    "restart": {
        "enabled": false,
        "shutdownTimeout": 3
    },
    "autoUpdate": true,
    "maxConcurrentDownloads": 4,
    "forceUpdate": "",
    "processes": [],
	"filteroverrides": {
		"sku": "FORC-FDEV-DO-1000", 
		"filter": "edo"
	}
}

With this edit, the game runs, but even with the "/edh" switch, it still runs Odyssey. And with the "/edo" switch, it will not run the game at all. 

Let me know what I might try to run Horizons using the Min-Ed-Launcher. I attach the current version of the setting.json file, and the log file that results from using this file and the '/edh' switch. 

Thank you for your support.


[min-ed-launcher (with filteroverrides in settings).log](https://github.com/rfvgyhn/min-ed-launcher/files/9646972/min-ed-launcher.with.filteroverrides.in.settings.log)
[settings.json.txt](https://github.com/rfvgyhn/min-ed-launcher/files/9647001/settings.json.txt)

**Comment by rfvgyhn** [comment]
That was close. Just missing two brackets.

```json
{
    "apiUri": "https://api.zaonce.net",
    "watchForCrashes": false,
    "language": null,
    "autoUpdate": true,
    "maxConcurrentDownloads": 4,
    "forceUpdate": "",
    "processes": [],
    "filterOverrides": [
        { "sku": "FORC-FDEV-DO-1000", "filter": "edo" }
    ],
    "additionalProducts": []
}
```

For future reference, you can find a sample settings file in the readme.md file at the bottom of the settings section.

**Comment by ZekeWolf** [comment]
Got it. I will test it out this evening when I return from work and let you
know the result.

**Comment by ZekeWolf** [comment]
I was finally able to make those revisions and it works!  /edh starts Horizons; /edo starts Odyssey. I have successfully created separate shortcuts that run off of my Steam installation. Thank you for the help. 

I have a separate account for Odyssey through Epic; and I may have a question about how to set up separate shortcuts to run Odyssey or Horizons off of my Epic account. But I will post a separate issue for that. This issue can be closed. 

Again, thank you.
