### ISSUE TITLE
Issues with EDMC launching

### ISSUE THREAD

**Issue by DeltaVista** [rfvgyhn/min-ed-launcher#64]
I am not a programmer, so it is hard for me to tell what is wrong with the code, but it simply will not launch EDMC along with the game itself. Maybe it is not how this feature is intended to work, but if it should work like this, I need assistance.
The path to the EDMC plugin .exe is - "C:\Program Files (x86)\EDMarketConnector\EDMarketConnector.exe"
It shows the following lines in terminal, but it runs only the game itself. EDMC never appears in active processes after that. Only if I run it manually from this file.
[23:38:08 INF] Starting process C:\Program Files (x86)\EDMarketConnector\EDMarketConnector.exe
[23:38:08 INF] Launching Elite Dangerous: Horizons (4.0)

And the code I used in \AppData\Local\min-ed-launcher\settings.json file is:

{
  "apiUri": "https://api.zaonce.net",
  "watchForCrashes": false,
  "gameLocation": null,
  "language": "en",
  "autoUpdate": true,
  "maxConcurrentDownloads": 4,
  "forceUpdate": "PUBLIC_TEST_SERVER_OD",
  "processes": [
    {
      "fileName": "C:\\Program Files (x86)\\EDMarketConnector\\EDMarketConnector.exe",
      "arguments": "--arg1 --arg2"
    },
  ],
  "filterOverrides": [
    { "sku": "FORC-FDEV-DO-1000", "filter": "edo" },
    { "sku": "FORC-FDEV-DO-38-IN-40", "filter": "edh4" }
  ],
  "additionalProducts": [{
    "filter": "edh4",
    "directory": "elite-dangerous-odyssey-64",
    "serverargs": "",
    "gameargs": "SeasonTwo",
    "sortkey": "04",
    "product_name": "Elite Dangerous: Horizons (4.0)",
    "product_sku": "FORC-FDEV-DO-38-IN-40"
  }]
}

![2022-10-01](https://user-images.githubusercontent.com/114833573/193427770-54813c50-b1ea-43c8-b827-7257bfe27826.png)
![2022-10-01 (1)](https://user-images.githubusercontent.com/114833573/193427775-43269948-693c-4ede-b8eb-567a1af2b788.png)

**Comment by rfvgyhn** [comment]
I see a few things to try:
1. Backslashes need to be escaped so you'll want `\\` instead of `\`
2. The trailing comma might be an issue so try removing it
3. Remove the `arguments` property unless there's EDMC specific arguments you need. `--arg1 --arg2` are just samples for the readme

```json
{
    "apiUri": "https://api.zaonce.net",
    "watchForCrashes": false,
    "gameLocation": null,
    "language": "en",
    "autoUpdate": true,
    "maxConcurrentDownloads": 4,
    "forceUpdate": "PUBLIC_TEST_SERVER_OD",
    "processes": [
        {
            "fileName": "C:\\Program Files (x86)\\EDMarketConnector\\EDMarketConnector.exe"
        }
    ],
    "filterOverrides": [
        {
            "sku": "FORC-FDEV-DO-1000",
            "filter": "edo"
        },
        {
            "sku": "FORC-FDEV-DO-38-IN-40",
            "filter": "edh4"
        }
    ],
    "additionalProducts": [
        {
            "filter": "edh4",
            "directory": "elite-dangerous-odyssey-64",
            "serverargs": "",
            "gameargs": "SeasonTwo",
            "sortkey": "04",
            "product_name": "Elite Dangerous: Horizons (4.0)",
            "product_sku": "FORC-FDEV-DO-38-IN-40"
        }
    ]
}
```

**Comment by DeltaVista** [comment]
It seems that github changed the code, `\\` was totally there, as the game would not even launch with `\`

I have tried using this code instead and it works now. Not sure if it is the trailing comma or arguments, or both, but it worked. Thank you so much!

Is there any way I can support this project on my side?

**Comment by rfvgyhn** [comment]
Just being a happy user is enough support for me. :)
