### ISSUE TITLE
Not launching 4.0 (steam)

### ISSUE THREAD

**Issue by Falken990** [rfvgyhn/min-ed-launcher#65]
I'm not really sure what I'm doing but I believe I've followed every direction properly yet the game either launches in Odyssey or 3.8 and i cannot get it into 4.0.
![Screenshot 2022-10-03 184907](https://user-images.githubusercontent.com/114960694/193699915-8f5444d6-b216-4247-a56a-f62fe50be74b.png)

Any help would be greatly appreciated. Thanks.

**Comment by rfvgyhn** [comment]
Have you added the EliteDangerous exe to the `processes` section in your settings file? If so, you should remove it. That section is for additional processes only.

If that doesn't fix it, can you post an entry from your [log file](https://github.com/rfvgyhn/min-ed-launcher#troubleshooting)?

**Comment by rfvgyhn** [comment]
If you just want access to edh4, your settings file should look like the following. No need for anything to be in the `processes` field.

```json
{
    "apiUri": "https://api.zaonce.net",
    "watchForCrashes": false,
    "language": null,
    "autoUpdate": true,
    "maxConcurrentDownloads": 4,
    "forceUpdate": "",
    "processes": [],
    "filterOverrides": [
        { "sku": "FORC-FDEV-DO-1000", "filter": "edo" },
        { "sku": "FORC-FDEV-DO-38-IN-40", "filter": "edh4" }
    ],
    "additionalProducts": [
        {
            "filter": "edh4",
            "directory": "elite-dangerous-odyssey-64",
            "serverargs": "",
            "gameargs": "SeasonTwo",
            "sortkey": "04",
            "product_name": "Elite Dangerous: Horizons (4.0)",
            "product_sku": "FORC-FDEV-DO-38-IN-40"
        }
    ]
}
```

If you want to compare it to the default settings file, you can check out [settings.json](https://github.com/rfvgyhn/min-ed-launcher/blob/master/src/MinEdLauncher/settings.json). That's the minimal amount of configuration you need. From there, you can start adding/modifying stuff to your liking.

**Comment by Falken990** [comment]
my settings file looks exactly like that yet it is still launching odyssey even with the proper steam launch options

**Comment by Falken990** [comment]
after trying again, it seems to be working now! thank you
