### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by JayeshRocks** [rfvgyhn/min-ed-launcher#67]
Basically i setup Min Ed according to the provided instructions, im using epic games, but instead of epic client I'm using legendary cuz that's way faster for my slow pc but when i confirmed that I'm fully setup and tried to run with legendary it works...
It detects my platform
Logs me in
Then checks for update and throws a error which i can't seem to resolve

Error:
[
Unhandled exception. System.MissingMethodException: Arg_MissingMethodException

at EosIF.LogHelper.Log(String Message)
at EosIF.EosInterface.Finalize()
]

I checked the min-ed launcher.log and last thing is can't find product "COMBAT_TRAINING_DEMO" disabling...

**Comment by rfvgyhn** [comment]
Can you check the [CI build](https://github.com/rfvgyhn/min-ed-launcher/actions/runs/3215453302) and verify this is fixed?

**Comment by JayeshRocks** [comment]
Thank you @rfvgyhn, using the CI build worked but still the normal release doesnt work does this mean that i have to use CI builds? Thanks

**Comment by rfvgyhn** [comment]
Yeah, for now. I'll make a new release soon that will include several fixes.
