### ISSUE TITLE
Unknown Platform. Failed to find Elite Dangerous install directory.

### ISSUE THREAD

**Issue by Falton0x1A** [rfvgyhn/min-ed-launcher#72]
Getting the 
`[##:##:## ERR] Unknown Platform. Failed to find Elite Dangerous install directory`

MinEDLauncher.exe is located in the folder; C:\Program Files (x86)\Steam\steamapps\common\Elite Dangerous where ED is installed with steam.

Win10 x64 Default Steam install.

Also tried modifying the json settings;
```
`{
    "apiUri": "https://api.zaonce.net",
    "watchForCrashes": false,
    "gameLocation": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Elite Dangerous\\EDLaunch.exe",
    "language": null,
    "autoUpdate": true,
    "maxConcurrentDownloads": 4,
    "forceUpdate": "",
    "processes": [],
    "filterOverrides": [
        { "sku": "elite-dangerous-64", "filter": "edo" },
        { "sku": "FORC-FDEV-DO-38-IN-40", "filter": "edh4" }
    ],
    "additionalProducts": []
}`
```

Below is my log file;
```
2022-11-12 00:30:29.848 +00:00 [INF] Elite Dangerous: Minimal Launcher - v0.7.3+486163a7
2022-11-12 00:30:29.942 +00:00 [DBG] 
    Args: [||]
    OS: Win64
    Env: 
    
2022-11-12 00:30:29.946 +00:00 [DBG] Reading settings from 'C:\Users\Falton\AppData\Local\min-ed-launcher\settings.json'
2022-11-12 00:30:30.119 +00:00 [ERR] Unknown platform. Failed to find Elite Dangerous install directory
```

**Comment by Falton0x1A** [comment]
I mistakenly copied all but one quotation mark for the steam launcher options;
`cmd /c "MinEdLauncher.exe %command% /autorun /autoquit /EDH`

should have been
`
cmd /c "MinEdLauncher.exe %command% /autorun /autoquit /EDH"`

**Comment by Roamcel** [comment]
I had trouble launching the game with min-ed, and turns out I also did this mistake, however I was getting the absurd
Platform: Dev
and
[ERR] Unhandled exception: System.NotImplementedException: Arg_NotImplementedException
messages at launch in the log.
Once I added the " at the end of the odyssey steam launch options,
cmd /c "MinEdLauncher.exe %command% /autorun /autoquit /edo"
the error was solved.
