### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by judgechuck** [rfvgyhn/min-ed-launcher#73]
Hi,

**Describe the bug/error**
I am running E:D through Steam on Windows 10. I added the line "cmd /c "MinEdLauncher.exe %command% /autorun /autoquit /EDH"" to the "General", "Launch Options" in Steam and I have tried running MinEdLauncher directly via command line (exe is located in same dir as EDLaunch.exe (E:\Steam\SteamApps\common\Elite Dangerous) and also just by double-clicking it. I also created a shortcut and added the parameters "/frontier profile /autorun /steam /autoquit /edh". All options return the below error and a Windows Crash Dump is also being created.

**Debug log**
Unhandled exception. System.TypeInitializationException: TypeInitialization_Type, <StartupCode$MinEdLauncher>.$MinEdLauncher.Log
 ---> System.Exception: HACK: No type found in 'Serilog.Sinks.Console, Version=4.1.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10' that implements ITextFormatter.
   at MinEdLauncher.Log.LoggerSinkConfiguration.ScrubbedConsole(LoggerSinkConfiguration, LogEventLevel)
   at <StartupCode$MinEdLauncher>.$MinEdLauncher.Log..cctor()
   Exception_EndOfInnerExceptionStack
   at MinEdLauncher.Log.get_logger()
   at MinEdLauncher.Program.main(String[])

Debug logging is placed in the standard log location for your operating system:
No log file created and no "%LOCALAPPDATA%\min-ed-launcher\" folder created.

Any ideas?

Edited to add: Sorry, I should say that I did check for similar "Unhandled Exception" issues, but they seemed related to Linux and not the same as the issue that I am seeing.

Regards,

JC

**Comment by rfvgyhn** [comment]
Thanks for the report. I didn't do thorough enough testing for the last release. Fix will be in the next release.

**Comment by judgechuck** [comment]
No problem and thanks, it's working perfectly now! :-)
