### ISSUE TITLE
feature request: relaunch mode, allow keypress for "launch immediately" as well as "don't relaunch"

### ISSUE THREAD

**Issue by slippycheeze** [rfvgyhn/min-ed-launcher#80]
If I run with `/relaunch 20` it gives me enough time to find the not-focused window and cancel launch before the timer ticks down.  I found that a smaller timeout can lead to accidental and annoying relaunch while I'm hunting around for the launcher.   (because windows isn't awesome, and it is not the focused thing when the ED client exits.)

Some of the time, though, that puts me there with 10-15 seconds left before relaunch, and I know I'd like to launch again.   It'd be nice if I could, eg, hit `<space>` and immediately relaunch, or anything else and cancel relaunch.

**Comment by rfvgyhn** [comment]
Added in b434321
