### ISSUE TITLE
/edh launches Live Horizons, not Legacy Horizons

### ISSUE THREAD

**Issue by Clockdistrict** [rfvgyhn/min-ed-launcher#81]
**Describe the bug/error**
using the `/edh` flag launches my game into the Live version of Horizons, not Legacy.

**Debug log**
[min-ed-launcher.log](https://github.com/rfvgyhn/min-ed-launcher/files/10454607/min-ed-launcher.log)

**Comment by rfvgyhn** [comment]
What do your launch options look like in steam? Your log shows you have both `/edh` and `/edh4` in your launch options. The launcher uses the last one specified.
