### ISSUE TITLE
Unknown platform. Failed to find Elite Dangerous install directory via shortcut

### ISSUE THREAD

**Issue by rfvgyhn** [rfvgyhn/min-ed-launcher#82]
Same issue here "Unknown platform. Failed to find Elite Dangerous install directory".

MinEdLauncher.exe in the exact same folder as EDLaunch.exe

**Edit**: It actually works when I start through the Steam Library, setting the launch option. But, then, I use this to have many shortcuts to start ED in VR and flat both in Odyssey and Horizon Legacy. I'm quite sure it's a common use case. And it used to work just fine before we had these last versions released. 

Soooooo. Is there a way to make it work like that again? Can we have multiple shortcuts pointing to different game options? Am I missing something here?

_Originally posted by @pilgerone in https://github.com/rfvgyhn/min-ed-launcher/issues/78#issuecomment-1399585609_

**Comment by rfvgyhn** [comment]
@pilegerone Can you provide your log output and what command you use in your shortcut files?

**Comment by pilgerone** [comment]
I actually got it to work now. I think you guys changed how the whole thing interacts with Steam. The "\steam" flag is gone. So now we have to launch it **through Steam**, but we can have multiple shortcuts, indeed.

Having a windows shortcut pointing to

"C:\Program Files (x86)\Steam\steam.exe" -gameidlaunch 359320 /edh /vr /autorun /autoquit

Actually works. As well as 

"C:\Program Files (x86)\Steam\steam.exe" -gameidlaunch 359320 /edo /autorun /autoquit

Sorry about the confusion. And many thanks for this wonderful piece of software. I recommend it whenever I get the chance.

**Comment by rfvgyhn** [comment]
Not sure I follow your meaning. There haven't been any changes to steam integration on windows since the initial release. The `/steam` flag is actually provided by [elite's steam config](https://steamdb.info/app/359320/config/) so you've never needed to manually specify it.

In any case, glad it's working for you.

**Comment by pilgerone** [comment]
Ah, dammit. I must've mixed everything up, then, as I remember having to set the /steam for it to work. I should've dug a bit deeper into the problem before posting an issue here. My bad.

I hope this helps someone with a similar issue, though. Kids, don't be like me, and save your shortcuts before formatting your system drives!

**Comment by OzDruiD** [comment]
@rfvgyhn Not sure if i should start a similar thread, have a friend with same issue, not detecting gamepath when using direct windows shortcuts.. even if we trry and force the gamepath variabvle in the settings file etc.

**Comment by rfvgyhn** [comment]
@OzDruiD Go ahead and start a new issue including your log and shortcut properties.
