### ISSUE TITLE
Unknown Platform: Unable to find Elite .... (v#3\new issue)

### ISSUE THREAD

**Issue by OzDruiD** [rfvgyhn/min-ed-launcher#83]
So similar to #78 and #82  - a friend cannot use Mini Launcher, to execute his steram install but from windows shortcuts.
gets the same error "unable to find elite" etc

I use normal steam to start the game launcher, and  mini launcher with restart to farm HGEs etc via a seperate windows shortcut.

The Target path of my Windows shortcut I tried to get him to use similar, except for replacing with his modfied directory path E:\xxxxx etc.

C:\Windows\System32\cmd.exe /c "D:\Steam\steamapps\common\ELITED~1\EDMini~1\MinEdLauncher.exe %command% /frontier <frontier acccount name> /autorun /autoquit /edo /restart 1"

A few items of import:- 
-  he cannot use   ELITED~1  -the   8.3  file name system\format to avoid directory name space as his windows file system does NOT exist\work in his windows 11  - yet does on mine.

-  we then modfied the Settings.JSON to especially point to his game path and still ont find\launch the game - any modfication of the json file resulted in large mount of errors as if it was corrupted (but it wasnt).
eg
"apiUri": "https://api.zaonce.net/",
    "watchForCrashes": false,
    "language": null,
    "gameLocation": "E:\Steam Games\steamapps\common\Elite Dangerous",
    "autoUpdate": true,
    "maxConcurrentDownloads": 100,
    "forceUpdate": "",

- configuring the steam launch paramers via the steam method works. however each time he wants to turn on the "Restart" option he has to edit steam launching options to add (or remove it)   - but it works.

Q.  To get it to find the game path - is there a better way to do it... and i notice in the ntoes you need to use special extra quotes for certain commands - if for example his game path has spaces and a different drive letter (even if mini launcher is in thaat same steam folder)  eg   E:\Steam Games\steamapps\common\Elite Dangerous,   - is there a certain way to configure the game location?  eg triple quotes?    and Windows shortccut path?

Q. If he has a STEAM RETAIL only account vs Frontier direct type account (lMine is Frontier Lifetimepass account, with a launch key for steam)- is it possible to even use this local windows shortcut method of launching and or the frontier profile?   As if he modfieds the internal STEAM settings - it works with mini launcher, but getting it to run direct from Windows with my shortcut above does not ?    Intead will he need to use the "Steam GAME ID" type shortcut method (I think in #82?"

With thanks,
PS.  I can try and get logs from my friend but may take a bit as he has almost given up at this point.
PPS.  I watched him \ helped him do this over remote view session so I know what he did, modified etc was all done correctly, ii just suspect we are doing the wrong process for his "version" if that makes sense?

Cheers,
DruiD

**Comment by OzDruiD** [comment]
Would we need to consider using a steam launch command instead of my frontier type launch command?  
eg
"E:\Steam Games\Steam.exe" -gameidlaunch 359320 /edo /autorun /autoquit /restart 1

instead of similar to my Windows ccommand lauinch method? (modified to his E:\Steam Games\ path etc

C:\Windows\System32\cmd.exe /c "E:\Steam Games\steamapps\common\ELITED1\EDMini1\MinEdLauncher.exe %command% /frontier /autorun /autoquit /edo /restart 1"

**Comment by rfvgyhn** [comment]
You can only use the `/frontier` option with a steam account if it was purchased before April 2019. That option completely bypasses steam and uses a regular frontier account.

It sounds like you'd need to use the steam launch command instead of directly pointing to the launcher exe.

As for specifying the path in the config file, Windows paths need escaped backslashes. `\\` instead of `\`.

**Comment by rfvgyhn** [comment]
It is needed because the config file is JSON and `\` is a special character in JSON. So when parsing JSON, you need to escape special characters if you want the literal character.

Ideally, I'd have chosen a more user friendly format for the config file (e.g. TOML), but I didn't consider it since I assumed I'd be the only person using it.

The example you gave looks correct.

**Comment by OzDruiD** [comment]
Ok thanks heaps.  appears he has a Aug 2019 steam edition so that explains a lot.
Will get him to try and steam GameID shortcut and also if necessary update the Settings.JSON.

I had hoped to achieve following by setting up different shortcuts
1. Normal Steam launch  via the normal steam library icon - launchs Mini Lauicher, with logging into EDO and quitting automaticaally
2.  Seperate Steam GAMEID launch shotcut on desktop - passing the addtional /Restart 1 command to farm HGEs

# I believe this %command% piece does in the configre windows\steam laucnh settings  allows multiple variables?
`Windows users - Set the value to cmd /c "MinEdLauncher.exe %command% /autorun /autoquit"`

- if it allows me to "pass" multiple parameters then the seprarate shortcut, adding just "/edo /restart 1"   might worrk to run oddessy and restart automatically, with the main Steam paramaters launching Mini Launcher with AutoRuin and AutoQuit as defaults.

So potential examples Win shortcuts (if steam sends minilauncher some default suffixes of of  /autorun and /autoquit)

`"E:\Steam Games\Steam.exe" -gameidlaunch 359320 /edo /restart 1`      - EDO and Restart after 1 second
"E:\Steam Games\Steam.exe" -gameidlaunch 359320 /edh4 /restart 3'  EDH and Retart after 3 seconds

**Comment by rfvgyhn** [comment]
Sounds like you've got it figured out.

`%command%` is a special steam substitution that the steam client populates with the correct path details and default launch parameters [configured by frontier](https://steamdb.info/app/359320/config/).

Any flags that you add to your shortcut will be appended to what's already configured in your launch options field within steam. If there are conflicting flags (e.g. `/steam /frontier`), the min launcher will use the last one specified.

**Comment by OzDruiD** [comment]
> Sounds like you've got it figured out.

Thanks so much for patience with it\me.   Its a lifesaver for myself and 1/2 myt squadron now that I am promoting it for things like HGE flipping and general time saving.   Much appreciate all your efforts.
