### ISSUE TITLE
Using without Steam running

### ISSUE THREAD

**Issue by ACyprus** [rfvgyhn/min-ed-launcher#9]
Hello, great project 👍 

I currently use a batch file to start the default launcher installed via Steam using,

`start "ED" "D:\Games\Steam\steamapps\common\Elite Dangerous\EDLaunch.exe" /vr /steam /autorun /autoquit`

The advantage here is Steam does not need to be running in the background, which helps free resources.

---

Is there any way to run your minimal launcher in a similar way, ie without Steam running? 

I tried to mimic my current setup using your launcher instead of the default and the error returned was

`Couldn't login: Unable to initialize Steam`

I appreciate your setup instructions do not cover this in any way, and that my question may be ludicrous to consider. I figured I'd ask just in case, and I hold you to no obligations or expectations.

Many thanks!

**Comment by Rfvgyhn** [comment]
It doesn't currently support this. The app doesn't store any credentials/tokens outside of memory at the moment. When I'm implementing #6, I can look into also storing tokens for Steam and Epic as well.

**Comment by ACyprus** [comment]
Thanks for considering it, much appreciated. 

Hope you're enjoying Hades :)

**Comment by Randshot** [comment]
@Rfvgyhn hey, is there any update on this? I would really like to be able to start the game without having steam open, especially since newly bought steam-versions of the game won't allow you to log-in without starting from steam.

**Comment by ACyprus** [comment]
@Randshot you can definitely run the game without Steam running, the ED launcher is able to work independently. 

I do this for Odyssey using the command line in my opening post above, I just add the switch `/EDO`

https://github.com/Rfvgyhn/min-ed-launcher/issues/9#issue-789437648

Perhaps

**Comment by Randshot** [comment]
> 
> 
> @Randshot you can definitely start the game without Steam running, the ED launcher is able to work independently.
> 
> I do this for Odyssey using the command line in my opening post above, I just add the switch `/EDO` and remove the VR one.
> 
> [#9 (comment)](https://github.com/Rfvgyhn/min-ed-launcher/issues/9#issue-789437648)
> 
> Perhaps this will help until min-ed supports it.
> 
> PS apologies for closing the issue, mistap.

Unfortunately that doesn't work for me. I have to have steam open (running in the background) for this to work. It seems like the ED launcher also uses the steam api to authenticate each time it starts. Dunno whether this is a bug, or intended.

**Comment by ACyprus** [comment]
Oh, wow, wonder how I get away with it then.

Sorry to hear that.

**Comment by Rfvgyhn** [comment]
I'm not positive what's going on. After reading more about steam session tickets, it looks like they are one time use tokens. So even if I had the launcher store them, you wouldn't be able to reuse it. You'd need to get a new one which would require steam to be running.

@ACyprus Was your account purchased from steam directly or from frontier and then they gave you a steam key to redeem it on steam? If the later, I'm wondering if it sees that steam isn't running so it falls back to logging in via your frontier account.

**Comment by ACyprus** [comment]
Yep, all bought through Steam, including the expansions.

**Comment by Randshot** [comment]
> 
> 
> I'm not positive what's going on. After reading more about steam session tickets, it looks like they are one time use tokens. So even if I had the launcher store them, you wouldn't be able to reuse it. You'd need to get a new one which would require steam to be running.
> 
> @ACyprus Was your account purchased from steam directly or from frontier and then they gave you a steam key to redeem it on steam? If the later, I'm wondering if it sees that steam isn't running so it falls back to logging in via your frontier account.

Would it be possible to give an option to store/start from saved tokens (the ones EDLaunch and min-ed-launcher use to actually start the game)? IIRC, those are valid for some amount of time. While not a perfect solution, it would be better than having to have steam open all the time.

**Comment by Rfvgyhn** [comment]
@ACyprus Hmm, I'm not sure then. I attempted to not cancel the auth ticket during cleanup and then re-use it but that resulted in unauthorized responses from FDev's api. I also can't get the default launcher to work without steam running. It's possible there's an auth flow that your account is using and mine isn't. I'd need to see the requests/responses to FDev's api to verify though. That would require you setting up something like [mitmproxy](https://mitmproxy.org/) and proxying EDLaunch.exe through it. Not sure if it's worth it to you to set all that up though.

@Randshot Yeah, that should be do-able.

Even if you did know F#, I'd say good luck with understanding the code base. :) This was the project I used to try and learn F#. It's a mess.

**Comment by Rfvgyhn** [comment]
@ACyprus Another thing to try is your frontier login. Instead of using the `/steam` flag, are you able to use `/frontier some-name` instead despite you buying steam?

**Comment by llorephie** [comment]
> @ACyprus Another thing to try is your frontier login. Instead of using the `/steam` flag, are you able to use `/frontier some-name` instead despite you buying steam?

Checked this behavior, worked for me :)

**Comment by Rfvgyhn** [comment]
@llorephie Thanks for the report. 

My hunch as to why offline mode works for some and not others is because FDev changed how steam licenses work for people that purchased the game starting from April 15th 2019. If that's the case, I think the only way to play in offline mode is to have a game license from before the switch and to use Frontier auth instead of Steam.

**Comment by ACyprus** [comment]
> @ACyprus Another thing to try is your frontier login. Instead of using the `/steam` flag, are you able to use `/frontier some-name` instead despite you buying steam?

Superb. I went through the reauth process to create the profile and it all works now!

Thanks so much for your work!


Incidentally, it tried to download an update for `FORC-FDEV-D-1010`, which I disabled by adding `"autoUpdate": false` to `settings.json` but I still need to hit enter at a prompt to skip the update.

```[22:01:09 INF] Checking for updates
[22:01:11 INF] Available Products:
        Elite Dangerous: Odyssey  FORC-FDEV-DO-1000 Up to Date
        Elite Dangerous: Horizons FORC-FDEV-D-1013  Up to Date
        Elite Dangerous           FORC-FDEV-D-1010  Requires Update
        Elite Dangerous: Arena    FORC-FDEV-D-1012  Up to Date
Select product(s) to update (eg: "1", "1 2 3") (default=None):
```

Is there any way to skip this step entirely without intervention?

**Comment by ACyprus** [comment]
Followup to my previous post, I deleted the `FORC-FDEV-D-1010` folder (it seemed to contain 10Gigs of the 32bit version) and I no longer receive the prompt to update shown above.
