### ISSUE TITLE
Unable to log in tonight

### ISSUE THREAD

**Issue by Foebik** [rfvgyhn/min-ed-launcher#93]
Hey guys, I am unable to log into using this app tonight... been using it fine for over a year now. I was able to log in normally when I take this app out of the equation. But while using it I get the below error. While doing some of my own digging. I found in the json file that it is using https://api.zaonce.net. And when I go to that site, it is showing a 404 error page.

```
<data>
<status>404</status>
<message>Not Found</message>
</data>

```

![image](https://user-images.githubusercontent.com/6633492/234737677-43bd5f43-9f1f-4b8b-9b27-27798f38de23.png)

**Comment by Foebik** [comment]
Using the root "zaonce.net" domain does redirect me to Frontier (https://www.frontierstore.net/).

**Comment by rfvgyhn** [comment]
Can you post the contents of your [log file](https://github.com/rfvgyhn/min-ed-launcher#troubleshooting)?

`https://api.zaonce.net` is the base uri for Frontier's API so a 404 when trying to view it in your browser is expected.

**Comment by Foebik** [comment]
Here you go. And thank you for the quick response.

[min-ed-launcher.log](https://github.com/rfvgyhn/min-ed-launcher/files/11338768/min-ed-launcher.log)

**Comment by Foebik** [comment]
Also, not always, but sometimes I got this error in the cmd prompt. 

 Couldn't login: Couldn't parse json - ExpectedStartOfValueNotFound, < LineNumber: 0 | BytePositionInLine: 0.

**Comment by ColonialDagger** [comment]
Not OP, but having the same issue. Here's my log file in case it helps:

[min-ed-launcher.log](https://github.com/rfvgyhn/min-ed-launcher/files/11338855/min-ed-launcher.log)

**Comment by rfvgyhn** [comment]
Looks like I'm getting the same. The API isn't returning a JSON document like it normally does. It's only happening with my steam account though; my epic account works fine.

It's possible they've updated their API to expect something that min-ed-launcher isn't sending. I'll have to do some digging.

**Comment by Foebik** [comment]
I know my Steam client updated twice tonight.

**Comment by Cirnesco** [comment]
Having the same exact issue.

[min-ed-launcher.log](https://github.com/rfvgyhn/min-ed-launcher/files/11338916/min-ed-launcher.log)

Unlinking and linking my accounts fixed it for one launch, but then it went back to the same error afterwards.

**Comment by rfvgyhn** [comment]
I'm thinking this might be a Steam issue. The default launcher no longer logs me in. It [appears to be the same for others](https://forums.frontier.co.uk/threads/cannot-access-account.616464/) as well. I _think_ the default launcher caches auth tokens for a while so it might be the case that it worked before because our login info was re-used.

**Comment by MichaelArthurLong** [comment]
Seems like going switching Steam to the beta branch might fix it.
![image](https://user-images.githubusercontent.com/13504249/234769371-cf90a5e0-6027-4c6e-9cd8-7e59d267110d.png)

**Comment by Cirnesco** [comment]
Didn't work for me personally. Default launcher works just fine, guess I'll just use that until Valve or FDev push a fix.

**Comment by rfvgyhn** [comment]
I see frontier has listed the [issue](https://issues.frontierstore.net/issue-detail/59193) as fixed. I was able to login normally a few minutes ago. Is anyone still unable to login?

**Comment by Foebik** [comment]
First time I tried I got this error.
![image](https://user-images.githubusercontent.com/6633492/235033720-fb2ddc9b-9efc-4171-b87c-cfae7b29a7f2.png)

Second time, worked.
