### ISSUE TITLE
NO SELECTED PROJECT

### ISSUE THREAD

**Issue by ardgndg** [rfvgyhn/min-ed-launcher#95]
**Describe the bug/error**
I have done all the steps I believe but I get no selected project error.

[min-ed-launcher.log](https://github.com/rfvgyhn/min-ed-launcher/files/11360065/min-ed-launcher.log)

**Comment by rfvgyhn** [comment]
`/edh4` is for the live version of horizons. Frontier has steam setup to download the legacy version. You'll need to follow the _Users that don't own the Odyssey DLC_ section of [this page](https://github.com/rfvgyhn/min-ed-launcher/discussions/54) to get min-ed-launcher to install it, use the default launcher to install it, wait for Frontier to update how steam delivers their game files or use `/edh` to launch the legacy version.
