### ISSUE TITLE
Trying to login into steam install as frontier (without steam, frontier launcher does work without it)

### ISSUE THREAD

**Issue by anzial** [rfvgyhn/min-ed-launcher#96]
Hi there, I'm trying to play the game without the necessity of launching steam. I did buy it from steam a long ago and it does allow launching the game using frontier launcher without steam, but I can't figure out how to configure the min ed launcher to do the same. Mini ed works from steam but not without it. I get sort of login issues, even though if I just launch the frontier launcher, it's logged in. Here's the output of the mini ed when I try to launch the game without steam

Unhandled exception: System.NotImplementedException: Arg_NotImplementedException
   at MinEdLauncher.Api.authenticate@142.MoveNext()
   at MinEdLauncher.App.authenticate@20-9.MoveNext()
   at MinEdLauncher.App.login@35-4.MoveNext()
   at MinEdLauncher.App.run@285-4.MoveNext()
   at MinEdLauncher.App.run@258.MoveNext()
   at MinEdLauncher.Program.run@65-21.MoveNext()
   at MinEdLauncher.Program.run@63-20.MoveNext()
   at MinEdLauncher.Program.run@62-19.MoveNext()
   at MinEdLauncher.Program.run@72-22.MoveNext()
   at MinEdLauncher.Program.run@75-23.MoveNext()
   at MinEdLauncher.Program.main(String[])

Any suggestions?

**Comment by rfvgyhn** [comment]
Are you providing the `/frontier profile-name` argument when you try to launch it? `NotImplementedException` looks like it's trying to authenticate in `dev` mode.

A [log file](https://github.com/rfvgyhn/min-ed-launcher#troubleshooting) should have been created which would provide more details. Can you post a run from that file (or the whole file)?

**Comment by anzial** [comment]
yeah, I'm kinda stomped with the profile-name. In the end, I logged into frontier site and took the code off there, I guess it's still wrong? it's was a short alphanumeric string.

**Comment by Fixitman333** [comment]
I misunderstood how "profile-name" worked initially. It appears it has nothing to do with your account. It's apparently just a name you choose, which links the shortcut to a .cred file on your PC. The .cred file contains your login credentials so you don't have to login every time. Profile-name cannot contain any spaces. My primary account's EDO shortcut looks like this:

"E:\Elite Dangerous\EDLaunch\MinEdLauncher.exe" /frontier **Fixitman_MK1** /autorun /autoquit /edo

My commander for this shortcut is named **Fixitman MK1** (no underscore). I believe I could have used something like **FM1** as well, as the name is up to the user.

Providing the full target line from your shortcut might be helpful.

**Comment by anzial** [comment]
I don't have a .cred file. My shortcut looks like yours, just different name, which I guess is meaningless. I guess I can't figure out how to identify my "profile-name"

**Comment by rfvgyhn** [comment]
The docs aren't too clear on this point. _profile-name_ can be anything you want. It's just a way for the launcher to differentiate between multiple accounts.

The log you provided is missing the first couple entries that shows what the launch arguments are. 

My next guess would be there's a space/quoting issue in your shortcut. If there's a space in the path to MinEdLauncher.exe, it will need to be wrapped in quotes, similar to how @Fixitman333 has theirs setup. You'll also want to avoid spaces in the profile name.

**Comment by anzial** [comment]
Sorry for missing arguments, empty space between them and the rest of the log have thrown me off. 
2023-05-13  [INF] Elite Dangerous: Minimal Launcher - v0.8.2+4646842b
2023-05-13  [DBG] 
    Args: [|"-frontier"; "****"; "/autorun"; "/autoquit"; "/edh4"|]
    OS: Win64
    Env: 


Arguments are standard but again, I can't figure out what I should use for the profile-name (like I said, I used alphanumeric Frontier ID off their website). No cred file to use either, is it supposed to be the same directory as the log and settings.json? I'm stomped on how to create it.

**Comment by rfvgyhn** [comment]
`-frontier` should be `/frontier`.

You can use whatever you want for profile-name. When I test, it's usually `/frontier asdf`. If you have multiple frontier accounts, you could use `/frontier asdf1` and `/frontier asdf2`. Commander name makes sense too since it's easy to remember and identify which account you are logging into.

You won't have a .cred file until you've logged in with your account credentials which won't happen until it recognizes the frontier flag. More details on the .cred file can be found in the [account-via-steam-or-epic](https://github.com/rfvgyhn/min-ed-launcher#frontier-account-via-steam-or-epic) section of the readme.

**Comment by anzial** [comment]
Well I'll be damned, thank you so much, I feel like a fool, such a small error. It worked :)
