### ISSUE TITLE
Launching via edLauncher screen goes blank

### ISSUE THREAD

**Issue by spherelance** [rfvgyhn/min-ed-launcher#98]
Got a strange one. Launching the game via steam everything goes fine, you see the initial video, etc.

Launching via edLaucher you hear the audio of initial video but the screen is black.

Attached is the log, if you need extra info just ask.
[min-ed-launcher.log](https://github.com/rfvgyhn/min-ed-launcher/files/11540695/min-ed-launcher.log)

**Comment by rfvgyhn** [comment]
I haven't had a chance to look at this yet, but I have seen the black screen issue when the launcher wouldn't pass on all the correct proton info. Do you have the same issue with different versions of proton?

**Comment by spherelance** [comment]
Tried it with Proton 8.0-2 and it worked. Tried it with GE-Proton 8.1, 8.2 & 8.3 and it didn't so looks like it is something GE-Proton does different that edLauncher is having a problem with.

**Comment by rfvgyhn** [comment]
I just tried out GE 8.4 and I didn't run into any issues. 

When you say launching via steam, you mean the default launcher right? Or are you launching the min launcher outside of steam?

Maybe there's a video card/driver issue? I'm using an AMD RX 5700 with Mesa 23.1.2.

To compare the arguments steam passes on, you can look at the `Args` section of the log file (the entry after `[INF] Elite Dangerous: Minimal Launcher - v...`). That won't show you env vars though. To do that, you'd have to change your launch options to point to a shell script that inspects them with something like `printenv`.

**Comment by spherelance** [comment]
I've changed the steam launch options to: alacritty -e ./MinEdLauncher %command% /autorun /autoquit /edo

When I have GE 8.4 set I see a black screen but hear the music, with non-GE 8.0-2 it shows the loading screen.

If I use the default steam launcher (ie not using MinEd) it'll load fine with GE and non-GE proton

I've a nVidia GeForce GTX 1650 driver 525.116.04

**Comment by spherelance** [comment]
Tried again using gnome-terminal and it worked so looks like it isn't a MinEd issue

Thanks for the time you've spent though
